title: Audrey Ming Wai Yip # your name (or website title) here
logo: "/images/IMG_7053.JPG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hello! I'm Audrey, welcome to my website!
  <br><br>
  I'm a final-year undergraduate student at Wellesley College studying Data Science with a concentration in Linguistics. My work sits at the intersection of language, technology, and society, where I use computational tools to analyze multilingual communication, digital discourse, and user behavior.
  I have conducted research across disciplines, including mapping the book trade in Early Modern London with the MIT Digital Humanities Lab to studying social media algorithm awareness at CMU. My current honors thesis, supported by the Levitt Fellowship, explores identity negotiation through Cantonese-English social media engagement.
  Beyond research, I enjoy tutoring linguistics, optimizing data workflows, and exploring the societal impact of invented languages. Feel free to check out my projects or connect with me!
  <br><br>
  <a href="https://www.linkedin.com/in/audreymwyip/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
